@startuml
class LeaderboardEntry {
    + Id : int <<get>> <<set>>
    + Score : int <<get>> <<set>>
    + UserId : int <<get>> <<set>>
}
LeaderboardEntry --> "DateAchieved" DateTime
LeaderboardEntry --> "User" User
@enduml
