@startuml
class Player {
    + ConnectionId : string <<get>> <<set>>
    + Y : int <<get>> <<set>>
    + Score : int <<get>> <<set>>
    + MatchId : string <<get>> <<set>>
    + IsLookingForMatch : bool <<get>> <<set>>
}
@enduml
